{
 "title": "Node - Network Overview",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "node",
  "network"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time_seconds, instance)"
   },
   {
    "name": "device",
    "query": "label_values(node_network_receive_bytes_total, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$node\"})",
     "legendFormat": "load1"
    },
    {
     "expr": "sum(node_load5{instance=~\"$node\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{instance=~\"$node\"})",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[3m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[3m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Network Utillization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[1m]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[1m]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"$device\",instance=~\"$node\"}[24h]))"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{device=~\"$device\",instance=~\"$node\"}[24h]))"
    }
   ]
  },
  {
   "title": "Netstat: TCP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{instance=~\"$node\"})",
     "legendFormat": "established"
    },
    {
     "expr": "sum(node_netstat_Tcp_ActiveOpens{instance=~\"$node\"})",
     "legendFormat": "activeOpens"
    },
    {
     "expr": "sum(node_netstat_Tcp_PassiveOpens{instance=~\"$node\"})",
     "legendFormat": "passiveOpens"
    },
    {
     "expr": "sum(node_netstat_Tcp_EstabResets{instance=~\"$node\"})",
     "legendFormat": "estabResets"
    },
    {
     "expr": "sum(node_netstat_Tcp_AttemptFails{instance=~\"$node\"})",
     "legendFormat": "attemptfails"
    },
    {
     "expr": "sum(node_netstat_Tcp_RetransSegs{instance=~\"$node\"})",
     "legendFormat": "retransSegs"
    }
   ]
  },
  {
   "title": "Netstat: UDP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m]))",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m]))",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m]))",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m]))",
     "legendFormat": "Udp_NoPorts"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_InCsumErrors{instance=~\"$node\"}[5m]))",
     "legendFormat": "Udp_InCsumErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_RcvbufErrors{instance=~\"$node\"}[5m]))",
     "legendFormat": "Udp_RcvbufErrors"
    },
    {
     "expr": "sum(irate(node_netstat_Udp_SndbufErrors{instance=~\"$node\"}[5m]))",
     "legendFormat": "Udp_SndbufErrors"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_nf_conntrack_entries_limit{instance=~\"$node\"}) - sum(node_nf_conntrack_entries{instance=~\"$node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "sum(node_nf_conntrack_entries_limit{instance=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}