{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "tags": [
  "gpu",
  "cluster",
  "hardware",
  "infrastructure"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "label_values(instance)" },
   { "name": "job", "label": "Prometheus Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Average Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_gpu_utilization{instance=~\"$host\",job=~\"$job\"}",
     "legendFormat": "_"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nv_gpu_utilization{instance=~\"$host\",job=~\"$job\"}",
     "legendFormat": "{{job}} @ {{instance}} - {{gpu_uuid}}"
    }
   ]
  },
  {
   "title": "GPU load - Power",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "nv_gpu_power_usage/nv_gpu_power_limit{instance=~\"$host\",job=~\"$job\"}",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "GPU load - Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes/nv_gpu_memory_total_bytes{instance=~\"$host\",job=~\"$job\"}",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "nv_gpu_power_usage{instance=~\"$host\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Energy consumption rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "joule" }
   ],
   "targets": [
    {
     "expr": "rate(nv_energy_consumption{instance=~\"$host\",job=~\"$job\"}[5m])",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Energy consumption in joules since the trtserver started",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "joule" }
   ],
   "targets": [
    {
     "expr": "nv_energy_consumption{instance=~\"$host\",job=~\"$job\"}",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  }
 ]
}