{
 "title": "Nvidia GPU - Inference stats",
 "description": "GPU dashboard for nvidia metrics ",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "label_values(instance)" },
   { "name": "model", "label": "Model", "query": "label_values(model)" }
  ]
 },
 "panels": [
  {
   "title": "Inference count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(nv_inference_count{model=~\"$model\",instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "Inference Request Success by GPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_request_success{model=~\"$model\",instance=~\"$host\"}[5m])",
     "legendFormat": "{{model}} running at {{instance}}"
    }
   ]
  },
  {
   "title": "Number of model executions performed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_exec_count{instance=~\"$host\",model=~\"$model\"}[5m])",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Inference queuing duration in microseconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us{instance=~\"$host\",model=~\"$model\"}[5m])",
     "legendFormat": "{{job}} @ {{instance}} - {{model}}"
    }
   ]
  },
  {
   "title": "Inference request duration in microseconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_request_duration_us{instance=~\"$host\",model=~\"$model\"}[5m])",
     "legendFormat": "{{job}} @ {{instance}} - {{model}}"
    }
   ]
  },
  {
   "title": "Inference compute duration in microseconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(nv_inference_compute_duration_us{instance=~\"$host\",model=~\"$model\"}[5m])",
     "legendFormat": "{{job}} @ {{instance}} - {{model}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "nv_gpu_power_usage{instance=~\"$host\"}"
    }
   ]
  }
 ]
}