apiVersion: v1
kind: Service
metadata:
  name: inference-svc
  namespace: default
  labels:
    app: inference-server-aws-test
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: http
      name: http-inference-server
    - port: 8001
      targetPort: grpc
      name: grpc-inference-server
    - port: 8002
      targetPort: metrics
      name: metrics-inference-server
  selector:
    app: inference-server-aws-test
